### PR TITLE
Fix a bunch of accessibility issues

### PR DESCRIPTION
**Pull request by ooade**
Fixes all the errors and a few issues.
Screenshot 2020-10-06 at 07 36 09

### CODE REVIEW

**Comment by Developerayo** [comment]
Nice!!
But the builds are failing, know why?

**Comment by ooade** [comment]
Skip to content:
Screenshot 2020-10-07 at 20 11 00

**Comment by ooade** [comment]
> Nice!!
> But the builds are failing, know why?

No idea.

**Comment by ooade** [comment]
@Developerayo The issue has been fixed. It should work fine now.

**Comment by Developerayo** [comment]
> @Developerayo The issue has been fixed. It should work fine now.

We are good! Thanks Man!

**Pull request merged**
